# NOTE: Generated By HttpRunner v3.1.3
# FROM: testcases\查看拣货任务明细.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase查看拣货任务明细(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/wms/saleoutDetail/selectListSaleoutIdBygood.do")
            .post(
                "http://api.wms.jc-test.cn/wms/saleoutDetail/selectListSaleoutIdBygood.do"
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "32",
                    "Content-Type": "application/x-www-form-urlencoded",
                    "Host": "api.wms.jc-test.cn",
                    "Origin": "http://pc.wms.jc-test.cn",
                    "Referer": "http://pc.wms.jc-test.cn/",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
                    "loginToken": "17362313866PC269F5565F33DA9A750D44602B9A79FD7",
                    "optDevice": "PC",
                }
            )
            .with_data({"reqParam": '{"id":688035}'})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 200)
            .assert_equal("body.msg", "成功！")
        ),
    ]


if __name__ == "__main__":
    TestCase查看拣货任务明细().test_start()
