# NOTE: Generated By HttpRunner v3.1.3
# FROM: testcases\查看待分配订单.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase查看待分配订单(HttpRunner):

    config = Config("WMS接口测试-待分配订单").verify(False)

    teststeps = [
        Step(
            RunRequest("/wms/allocated/selectPage.do")
            .post("http://api.wms.jc-test.cn/wms/allocated/selectPage.do")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "54",
                    "Content-Type": "application/x-www-form-urlencoded",
                    "Host": "api.wms.jc-test.cn",
                    "Origin": "http://pc.wms.jc-test.cn",
                    "Referer": "http://pc.wms.jc-test.cn/",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
                    "loginToken": "17362313866PC269F5565F33DA9A750D44602B9A79FD7",
                    "optDevice": "PC",
                }
            )
            .with_data({"reqParam": '{"pageNum":1,"pageSize":15}'})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 200)
            .assert_equal("body.msg", "成功！")
        ),
    ]


if __name__ == "__main__":
    TestCase查看待分配订单().test_start()
